In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
# 2-d Lists/ array in pure python

lst = [
    [1,2,3],
    [4,5,6]
]
lst

[[1, 2, 3], [4, 5, 6]]

In [2]:
for row in lst:
    for ele in row:
     print(ele,end="  ")
    print()

1  2  3  
4  5  6  


In [3]:
# do it yourself
# iterate over 2-d arrays but using Range() function
for i in range(0,len(lst)):
    for j in range(0,len(lst[i])):
        print(lst[i][j],end=" ")
    print()

1 2 3 
4 5 6 


### Numpy


Why Numpy?
* Using python lists under the hood is not possible because of thousands of computations while working with data
* Numpy uses C language under the hood which is lightning fast as compared to python.
* Pandas is written over numpy

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

# pip install numpy
# pip install pandas
# pip install matplotlib

### Data-types and attributes

In [6]:
# numpy's main data type is ndarray

In [5]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
type(arr)


numpy.ndarray

In [7]:
arr.shape

(3,)

In [8]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
print(type(arr1))
arr1


<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr1.shape

(2, 3)

In [10]:
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(type(arr2))
arr2
# dim - 3 x 3

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr2.shape

(3, 3)

In [13]:
arr3 = np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                 [[23,34.5,77.0],
                 [98,55,34],
                 [101,2.5,7]]])
print(type(arr3))
arr3

<class 'numpy.ndarray'>


array([[[  1. ,   2. ,   3. ],
        [  4. ,   5. ,   6. ],
        [  7. ,   8. ,   9. ]],

       [[ 23. ,  34.5,  77. ],
        [ 98. ,  55. ,  34. ],
        [101. ,   2.5,   7. ]]])

In [14]:
arr3.shape

(2, 3, 3)

In [ ]:
# Attributes --> arr.shape
# & Methods --> arr.mean()


In [15]:
arr1.shape

(2, 3)

In [16]:
arr2.shape

(3, 3)

In [17]:
# check shapes of arr
arr3.shape

(2, 3, 3)

In [18]:
arr.ndim

1

In [19]:
arr1.ndim

2

In [20]:
arr2.ndim

2

In [21]:
# .ndim of arrays

arr3.ndim

3

In [26]:
# .dtype of arrays
temp = np.array([1.6,3,6])
temp.dtype

dtype('float64')

In [27]:
arr.size

3

In [28]:
arr1.size

6

In [29]:
arr2.size

9

In [30]:
# .size of arrays
arr3.size


18

### Creating Arrays automatically

In [31]:
sample = np.ones(3)
print(sample.dtype)
sample

float64


array([1., 1., 1.])

In [32]:
sample = np.ones((3,3))
print(sample.dtype)
sample

float64


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
sample = np.ones((3,3,3))
print(sample.dtype)
sample

float64


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
identity = np.eye(3,3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
identity = np.eye(3,5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [44]:
#You can create only 1d array
range_array = np.arange(0,10,1)  # start, stop, step
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
random = np.random.randint(1,100)
random

48

In [52]:
random_array = np.random.randint(1,100,size=20)
random_array

array([66, 20, 27, 30, 83, 80, 77, 51, 11, 10, 71, 43, 17, 19, 39, 17, 59,
       52, 57, 20])

In [53]:
random_matrix = np.random.randint(1,100,size=(3,3))
random_matrix

array([[32, 96, 85],
       [19, 45,  4],
       [31, 83, 12]])

In [54]:
random_matrix = np.random.randint(1,100,size=(2,3,4))
random_matrix

array([[[41, 67, 12, 51],
        [24, 67, 48, 56],
        [64, 99, 31, 68]],

       [[ 6, 33, 21, 69],
        [63, 49, 17, 28],
        [20, 53, 26, 59]]])

In [55]:
# for an array between 0 & 1
random_matrix = np.random.random(size=10)
random_matrix

array([0.1938231 , 0.22480613, 0.43683533, 0.80497132, 0.04687789,
       0.57620628, 0.1449037 , 0.83815614, 0.87493211, 0.64861715])

In [56]:
# for an array between 0 & 1
random_matrix = np.random.random(size=(3,3))
random_matrix

array([[0.18673212, 0.05169143, 0.3169267 ],
       [0.88657175, 0.3321389 , 0.49969555],
       [0.6675554 , 0.31134099, 0.22171043]])

In [57]:
# for an array between 0 & 1
random_matrix = np.random.random(size=(2,2,6))
random_matrix

array([[[0.1406553 , 0.23583444, 0.46472147, 0.09188414, 0.35191114,
         0.93594462],
        [0.45222081, 0.75864427, 0.30505028, 0.55044195, 0.82651637,
         0.34674351]],

       [[0.2889408 , 0.71075412, 0.17052097, 0.58074407, 0.57340297,
         0.26318868],
        [0.37887108, 0.15962513, 0.05036457, 0.8691382 , 0.04348704,
         0.96502987]]])

### Seeding to Reproduce no.

In [58]:
np.random.seed(100)
print(np.random.random())
np.random.seed(100)
print(np.random.random())

0.5434049417909654
0.5434049417909654


### Viewing and Indexing

In [59]:
# .unique
temp = np.array([1,22,22,3,4,5,5,99,99,22])
np.unique(temp)


array([ 1,  3,  4,  5, 22, 99])

In [60]:
arr

array([1, 2, 3])

In [61]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr3

array([[[  1. ,   2. ,   3. ],
        [  4. ,   5. ,   6. ],
        [  7. ,   8. ,   9. ]],

       [[ 23. ,  34.5,  77. ],
        [ 98. ,  55. ,  34. ],
        [101. ,   2.5,   7. ]]])

In [64]:
arr[0]

1

In [65]:
arr1[0]


array([1, 2, 3])

In [66]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
arr2[0]

array([1, 2, 3])

In [68]:
arr3

array([[[  1. ,   2. ,   3. ],
        [  4. ,   5. ,   6. ],
        [  7. ,   8. ,   9. ]],

       [[ 23. ,  34.5,  77. ],
        [ 98. ,  55. ,  34. ],
        [101. ,   2.5,   7. ]]])

In [69]:
arr3[0]

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [70]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr2[1:3]


array([[4, 5, 6],
       [7, 8, 9]])

In [72]:
print(arr2[1,2])
print(arr2[2][1])

6
8


In [73]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr2[:,2]


array([3, 6, 9])

#### Shallow copying 

In [80]:
import numpy as np
temp = np.arange(1,11,1)
temp

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
temp1 = temp
temp1[:5] = 99
temp[5] = 999
print(temp1)
print(temp)

[ 99  99  99  99  99 999   7   8   9  10]
[ 99  99  99  99  99 999   7   8   9  10]


In [81]:
temp = np.arange(1,11,1)
temp1 = temp.copy()
temp1[:5] = 99
print(temp)
print('*'*130)
print(temp1)


[ 1  2  3  4  5  6  7  8  9 10]
**********************************************************************************************************************************
[99 99 99 99 99  6  7  8  9 10]


In [84]:
arr3

array([[[  1. ,   2. ,   3. ],
        [  4. ,   5. ,   6. ],
        [  7. ,   8. ,   9. ]],

       [[ 23. ,  34.5,  77. ],
        [ 98. ,  55. ,  34. ],
        [101. ,   2.5,   7. ]]])

In [87]:
# for both the matrices in arr3 get first two rows and first two columns
arr3[:,0:2,0:2]


array([[[ 1. ,  2. ],
        [ 4. ,  5. ]],

       [[23. , 34.5],
        [98. , 55. ]]])

In [88]:
arr3[0:1,0:2,0:2]

array([[[1., 2.],
        [4., 5.]]])

In [89]:
arr3[1:2,0:2,0:2]

array([[[23. , 34.5],
        [98. , 55. ]]])

In [90]:
# complex array
arr4 = np.random.randint(10,size=(1,2,3,4,5))  # read dimensions from inside to outside
arr4

array([[[[[3, 7, 7, 0, 4],
          [2, 5, 2, 2, 2],
          [1, 0, 8, 4, 0],
          [9, 6, 2, 4, 1]],

         [[5, 3, 4, 4, 3],
          [7, 1, 1, 7, 7],
          [0, 2, 9, 9, 3],
          [2, 5, 8, 1, 0]],

         [[7, 6, 2, 0, 8],
          [2, 5, 1, 8, 1],
          [5, 4, 2, 8, 3],
          [5, 0, 9, 3, 6]]],


        [[[3, 4, 7, 6, 3],
          [9, 0, 4, 4, 5],
          [7, 6, 6, 2, 4],
          [2, 7, 1, 6, 6]],

         [[0, 7, 2, 3, 5],
          [4, 2, 4, 3, 7],
          [9, 0, 0, 5, 9],
          [6, 6, 5, 6, 4]],

         [[7, 3, 9, 2, 3],
          [8, 7, 1, 5, 9],
          [3, 0, 6, 2, 3],
          [4, 8, 9, 8, 5]]]]])

In [93]:
#  ok so get first 4 numbers of innermost arrays
arr4[:,:,0:1,0:1,:5]


array([[[[[3, 7, 7, 0, 4]]],


        [[[3, 4, 7, 6, 3]]]]])

### Manipulating arrays

In [94]:
arr

array([1, 2, 3])

In [99]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [100]:
arr + ones

array([2., 3., 4.])

In [101]:
arr-ones

array([0., 1., 2.])

In [102]:
arr * ones

array([1., 2., 3.])

In [103]:
arr

array([1, 2, 3])

In [104]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
# element - wise multiplication
arr * arr2  

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [106]:
arr / ones

array([1., 2., 3.])

In [107]:
arr

array([1, 2, 3])

In [108]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
arr2 / arr

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ],
       [7. , 4. , 3. ]])

In [110]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
arr2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [112]:

arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
np.log(arr1)


array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [114]:
np.exp(arr1)


array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [115]:
temp = np.array([1,4,9,36,64])
np.sqrt(temp)


array([1., 2., 3., 6., 8.])

### Aggregation
perform the same operation on a number of elements

In [116]:
lst = [1,2,3]
sum(lst)

6

In [117]:
np.sum(lst)

6

In [ ]:
# use pythonic functions with list and np's inbuilt function with numpy arrays

In [118]:
# alternatively cal the method directly off the array
arr1.sum()

21

In [119]:
# let's see how fast np is!!

massive = np.random.random(100000)
massive[:10]

array([0.1139206 , 0.36841365, 0.36074842, 0.88001849, 0.27454204,
       0.22458118, 0.81397318, 0.05820075, 0.73015342, 0.03267909])

In [120]:
%timeit sum(massive)  # Python's way of summing
print('-'*130)
%timeit np.sum(massive)   # Numpy (C) way's of summing
print('-'*130)
%timeit massive.sum()   # Numpy (C) way's of summing

7.14 ms ± 166 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
----------------------------------------------------------------------------------------------------------------------------------
42.8 µs ± 84.9 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
----------------------------------------------------------------------------------------------------------------------------------
40.6 µs ± 376 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


1 Milli = 1000 micro

In [121]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# mean,max,min,std,var,sqrt

In [122]:
np.max(arr2)

9

In [123]:
np.min(arr2)

1

In [124]:
np.mean(arr2)

5.0

In [125]:
np.std(arr2)

2.581988897471611

In [126]:
np.var(arr2)

6.666666666666667

In [127]:
np.sqrt(arr2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

The Standard Deviation is a measure of how spread out numbers are in data.   
The Variance is average of the squared differences from the Mean.    
Check out [here](https://www.mathsisfun.com/data/standard-deviation.html) for more in-depth maths.

#### Changing shapes of array


In [88]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
arr1.shape

(2, 3)

In [90]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
arr1.reshape(1,6)


array([[1, 2, 3, 4, 5, 6]])

In [92]:
arr1.reshape(6,1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [93]:
arr = np.random.randint(100,size=(6,3))

arr

array([[92, 62, 38],
       [50,  2, 92],
       [11, 41, 91],
       [81, 68,  0],
       [24, 55, 51],
       [35, 63, 44]])

In [94]:
#transpose
# Row --> Columns  &&  Columns --> Rows
arr.T

array([[92, 50, 11, 81, 24, 35],
       [62,  2, 41, 68, 55, 63],
       [38, 92, 91,  0, 51, 44]])

In [95]:
arr3

array([[[  1. ,   2. ,   3. ],
        [  4. ,   5. ,   6. ],
        [  7. ,   8. ,   9. ]],

       [[ 23. ,  34.5,  77. ],
        [ 98. ,  55. ,  34. ],
        [101. ,   2.5,   7. ]]])

In [96]:
arr3.shape

(2, 3, 3)

In [97]:
arr6=arr3.T
print(arr6)
arr6.shape

[[[  1.   23. ]
  [  4.   98. ]
  [  7.  101. ]]

 [[  2.   34.5]
  [  5.   55. ]
  [  8.    2.5]]

 [[  3.   77. ]
  [  6.   34. ]
  [  9.    7. ]]]


(3, 3, 2)

In [98]:
arr4 = np.array([[[1,2,3],
                  [4,5,6],
                  ],
                 [[23,34.5,77.0],
                 [98,55,34],
                 ]])
print(type(arr4))
print(arr4)
arr4.shape


<class 'numpy.ndarray'>
[[[ 1.   2.   3. ]
  [ 4.   5.   6. ]]

 [[23.  34.5 77. ]
  [98.  55.  34. ]]]


(2, 2, 3)

In [99]:
arr4.T

array([[[ 1. , 23. ],
        [ 4. , 98. ]],

       [[ 2. , 34.5],
        [ 5. , 55. ]],

       [[ 3. , 77. ],
        [ 6. , 34. ]]])

### Dot product
Resource to learn dot product is [here](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

In [100]:

a1 = np.random.randint(5,size=(5,3))
a1

array([[2, 1, 3],
       [1, 2, 1],
       [0, 3, 2],
       [0, 0, 1],
       [3, 4, 2]])

In [101]:
a2 = np.random.randint(5,size=(5,3))
a2

array([[3, 0, 1],
       [1, 3, 2],
       [1, 1, 3],
       [1, 2, 0],
       [1, 2, 0]])

In [102]:
# element wise
a1 * a2

array([[6, 0, 3],
       [1, 6, 2],
       [0, 3, 6],
       [0, 0, 0],
       [3, 8, 0]])

In [103]:
np.dot(a1,a2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [104]:
a1

array([[2, 1, 3],
       [1, 2, 1],
       [0, 3, 2],
       [0, 0, 1],
       [3, 4, 2]])

In [105]:
a2.T

array([[3, 1, 1, 1, 1],
       [0, 3, 1, 2, 2],
       [1, 2, 3, 0, 0]])

In [106]:
np.dot(a1,a2.T)


array([[ 9, 11, 12,  4,  4],
       [ 4,  9,  6,  5,  5],
       [ 2, 13,  9,  6,  6],
       [ 1,  2,  3,  0,  0],
       [11, 19, 13, 11, 11]])

In [107]:
a1.shape,a2.T.shape

((5, 3), (3, 5))

### Dot Product example (Nut-Butter Sale)

In [108]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [64]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [109]:

import pandas as pd
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [110]:
# Create prices 
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [111]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [112]:
# calculate total sales using dot product
np.dot(prices,sales_amounts)


ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [113]:
prices.shape,sales_amounts.shape

((3,), (5, 3))

In [70]:
prices

array([10,  8, 12])

In [71]:
sales_amounts.T

array([[12,  3,  9,  4,  1],
       [15,  3, 19,  6,  6],
       [ 0,  7, 18, 12,  7]])

In [72]:
total_sales = np.dot(prices,sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [73]:
weekly_sales["Total ($)"] = total_sales
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

### Comparison Operators

In [9]:
a3 = np.random.randint(10,size=(1,3))
a3

array([[8, 2, 1]])

In [10]:
a4 = np.random.randint(10,size=(1,3))
a4

array([[2, 0, 3]])

In [11]:
a3 > a4

array([[ True,  True, False]])

In [12]:
a3 >= a4

array([[ True,  True, False]])

In [13]:
bool_Array = a3 >= a4
type(bool_Array),bool_Array.dtype

(numpy.ndarray, dtype('bool'))

In [14]:
a3 > 5

array([[ True, False, False]])

In [15]:
a3 < 5

array([[False,  True,  True]])

In [16]:
a3==a3

array([[ True,  True,  True]])

In [17]:
a3!=a3

array([[False, False, False]])

In [18]:
a3==a4

array([[False, False, False]])

### Sorting

In [19]:
random_arr = np.random.randint(10,size=(3,5))
random_arr

array([[0, 4, 2, 2, 1],
       [1, 4, 5, 1, 2],
       [7, 0, 9, 7, 3]])

In [20]:
np.sort(random_arr)#row wise sorting


array([[0, 1, 2, 2, 4],
       [1, 1, 2, 4, 5],
       [0, 3, 7, 7, 9]])

In [21]:
random_arr = np.random.randint(10,size=(3,5))
random_arr

array([[7, 2, 8, 9, 9],
       [7, 9, 9, 6, 7],
       [3, 1, 4, 6, 6]])

In [22]:
np.sort(random_arr,axis=0)#columwise sorting

array([[3, 1, 4, 6, 6],
       [7, 2, 8, 6, 7],
       [7, 9, 9, 9, 9]])

In [23]:
# sort the indices

a5 = np.array([3,1,2])
np.argsort(a5)


array([1, 2, 0], dtype=int64)

In [24]:
random_arr

array([[7, 2, 8, 9, 9],
       [7, 9, 9, 6, 7],
       [3, 1, 4, 6, 6]])

In [25]:
# Returns the indices that would sort an array.
np.argsort(random_arr)

array([[1, 0, 2, 3, 4],
       [3, 0, 4, 1, 2],
       [1, 0, 2, 3, 4]], dtype=int64)

In [26]:
random_arr

array([[7, 2, 8, 9, 9],
       [7, 9, 9, 6, 7],
       [3, 1, 4, 6, 6]])

In [27]:
# index of max number
np.argmax(random_arr)


3

In [28]:
# index of min number
np.argmin(random_arr)


11

In [29]:
# Axis 
random_arr

array([[7, 2, 8, 9, 9],
       [7, 9, 9, 6, 7],
       [3, 1, 4, 6, 6]])

In [30]:
np.max(random_arr,axis=1) # GO HORIZONTALLY | GO ALONG COLUMNS


array([9, 9, 6])

In [31]:
np.max(random_arr,axis=0) # GO VERTICALLY | GO ALONG ROWS


array([7, 9, 9, 9, 9])

### Practical Example using Numpy

<img src="numpy-images/panda.png">

In [98]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [32]:

# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("numpy-images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [33]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [34]:
panda.size

24465000

In [35]:
panda.ndim

3

In [36]:
panda.shape

(2330, 3500, 3)

<img src="numpy-images/car-photo.png">

In [37]:
car = imread("numpy-images/car-photo.png")


In [38]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [39]:
car.size,car.ndim,car.shape

(991300, 3, (431, 575, 4))

<img src="numpy-images/dog-photo.png">

### Extra useful Function

In [42]:
#linspace or linearly space or equally spaced elements list/array

np.linspace(1,10,100)


array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [43]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])